services:
  MepProject\PhpBenchmarkRunner\Service\PhpBenchmarkRunner:
    public: true
    arguments:
      $annotationManager: '@php_benchmark_runner.annotation_mapper'


  MepProject\PhpBenchmarkRunner\Service\AnnotationMapper: ~

  php_benchmark_runner.runner:
    alias: MepProject\PhpBenchmarkRunner\Service\PhpBenchmarkRunner
    public: true


  php_benchmark_runner.annotation_mapper:
    alias: MepProject\PhpBenchmarkRunner\Helper\AnnotationMapper