services:
  MepProject\PhpBenchmarkRunner\Service\PhpBenchmarkRunner:
    public: true

  MepProject\PhpBenchmarkRunner\Service\AnnotationMapper: ~

  php_benchmark_runner.runner:
    alias: MepProject\PhpBenchmarkRunner\Service\PhpBenchmarkRunner
    public: true


  php_benchmark_runner.annotation_mapper:
    alias: MepProject\PhpBenchmarkRunner\Service\AnnotationMapper